version: '3'

networks:
  back-tier: null
volumes:
  db-data:

    null
services:
  db:
    image: postgres:14.1
    restart: always
    networks:
      - back-tier
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./.mydb.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.insert.sql:/docker-entrypoint-initdb.d/insert.sql
      - ./task.sql:/docker-entrypoint-initdb.d/task.sql
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=mytestdb"

  adminer:
    networks:
      - back-tier
    image: adminer
    restart: always
    ports:
      - 8082:8080
